service:
  type: LoadBalancer
  
resources: 
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m #default 500m
    memory: 512Mi 

# Define separate resources per arbiter, which are less then primary or secondary
# used only when replica set is enabled
resourcesArbiter:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 100m #default 500m
    memory: 512Mi

ingress:
  enabled: true
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - mongodb.admin.dev.ubivius.tk
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

